services:

  postgres:
    image: postgres:17
    container_name: maje-postgres-prod
    restart: unless-stopped

    env_file:
      - ./backend/.env.production

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend

    container_name: hardynatta-backend-prod
    restart: unless-stopped

    env_file:
      - ./backend/.env.production

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-H",
          "Host: api.maje.example.com",
          "http://localhost:8000/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_prod_data: