"""add refresh token family tracking

Revision ID: 569b89591841
Revises: d7f474ce4974
Create Date: 2026-08-02 14:26:39.953150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569b89591841'
down_revision: Union[str, Sequence[str], None] = 'd7f474ce4974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add token_family as nullable first so this migration
    # remains safe when legacy user_sessions rows exist.
    op.add_column(
        "user_sessions",
        sa.Column(
            "token_family",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.add_column(
        "user_sessions",
        sa.Column(
            "revoke_reason",
            sa.String(length=32),
            nullable=True,
        ),
    )

    # Give every legacy session its own stable family.
    # Existing sessions predate refresh-token lineage,
    # so they must not accidentally share a family.
    op.execute(
        """
        UPDATE user_sessions
        SET token_family =
            md5('maje-session-family-' || id::text)
            ||
            md5('maje-session-family-secondary-' || id::text)
        WHERE token_family IS NULL
        """
    )

    # All existing rows are now populated, so enforce
    # the invariant required by the ORM model.
    op.alter_column(
        "user_sessions",
        "token_family",
        existing_type=sa.String(length=64),
        nullable=False,
    )

    op.create_index(
        op.f("ix_user_sessions_token_family"),
        "user_sessions",
        ["token_family"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_token_family'), table_name='user_sessions')
    op.drop_column('user_sessions', 'revoke_reason')
    op.drop_column('user_sessions', 'token_family')
    # ### end Alembic commands ###
