"""add competition rounds table

Revision ID: 7e957ced7394
Revises: bd38ae157267
Create Date: 2026-08-06 06:52:31.769954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e957ced7394'
down_revision: Union[str, Sequence[str], None] = 'bd38ae157267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'code', name='uq_competition_rounds_competition_id_code')
    )
    op.create_index(op.f('ix_competition_rounds_competition_id'), 'competition_rounds', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_rounds_id'), 'competition_rounds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_rounds_id'), table_name='competition_rounds')
    op.drop_index(op.f('ix_competition_rounds_competition_id'), table_name='competition_rounds')
    op.drop_table('competition_rounds')
    # ### end Alembic commands ###
