"""add competition round entries

Revision ID: 83413bfd2d69
Revises: 7e957ced7394
Create Date: 2026-08-06 08:03:02.982429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83413bfd2d69'
down_revision: Union[str, Sequence[str], None] = '7e957ced7394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_round_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_round_id', sa.Integer(), nullable=False),
    sa.Column('competition_registration_id', sa.Integer(), nullable=False),
    sa.Column('performance_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_registration_id'], ['competition_registrations.id'], ),
    sa.ForeignKeyConstraint(['competition_round_id'], ['competition_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_round_id', 'competition_registration_id', name='uq_competition_round_entries_round_registration')
    )
    op.create_index(op.f('ix_competition_round_entries_competition_registration_id'), 'competition_round_entries', ['competition_registration_id'], unique=False)
    op.create_index(op.f('ix_competition_round_entries_competition_round_id'), 'competition_round_entries', ['competition_round_id'], unique=False)
    op.create_index(op.f('ix_competition_round_entries_id'), 'competition_round_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competition_round_entries_id'), table_name='competition_round_entries')
    op.drop_index(op.f('ix_competition_round_entries_competition_round_id'), table_name='competition_round_entries')
    op.drop_index(op.f('ix_competition_round_entries_competition_registration_id'), table_name='competition_round_entries')
    op.drop_table('competition_round_entries')
    # ### end Alembic commands ###
